/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.NhaCungCapBUS;
import DAO.NhaCungCapDAO;
import DTO.NhaCungCapDTO;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class nhacungcap extends javax.swing.JPanel {

    /**
     * Creates new form nhacungcap
     */
    public nhacungcap() {
        initComponents();
        taoBangTk();
        hienthidsncc();
        cacChucNang();
    }

    private boolean validateFormNCC() {
        String idncc = txtIdncc.getText().trim();
        String name = txtName.getText().trim();
        String sdt = txtSdt.getText().trim();
        String diachi = txtDiachi.getText().trim();

        // Kiểm tra ID nhà cung cấp (phải là số)
        if (idncc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mã nhà cung cấp không được để trống!");
            return false;
        }
        try {
            Integer.parseInt(idncc); // Kiểm tra có phải số không
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Mã nhà cung cấp phải là số!");
            return false;
        }

        // Kiểm tra tên nhà cung cấp
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên nhà cung cấp không được để trống!");
            return false;
        }
        if (name.length() < 3 || name.length() > 50) {
            JOptionPane.showMessageDialog(this, "Tên nhà cung cấp phải từ 3 đến 50 ký tự!");
            return false;
        }
        if (!name.matches("^[a-zA-Z0-9 ]+$")) { // Chỉ cho phép chữ cái, số, và khoảng trắng
            JOptionPane.showMessageDialog(this, "Tên nhà cung cấp không được chứa ký tự đặc biệt!");
            return false;
        }

        // Kiểm tra số điện thoại
        if (sdt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không được để trống!");
            return false;
        }
        if (!sdt.matches("^[0-9]{10,11}$")) { // Chỉ cho phép số có 10-11 chữ số
            JOptionPane.showMessageDialog(this, "Số điện thoại phải từ 10 đến 11 số và chỉ chứa số!");
            return false;
        }

        // Kiểm tra địa chỉ
        if (diachi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Địa chỉ không được để trống!");
            return false;
        }
        if (diachi.length() < 5 || diachi.length() > 100) {
            JOptionPane.showMessageDialog(this, "Địa chỉ phải từ 5 đến 100 ký tự!");
            return false;
        }

        return true; // Nếu tất cả đều hợp lệ
    }

    private boolean validateFormAddNCC() {
        String name = txtName.getText().trim();
        String sdt = txtSdt.getText().trim();
        String diachi = txtDiachi.getText().trim();

        // Kiểm tra ID nhà cung cấp (phải là số)
        // Kiểm tra tên nhà cung cấp
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên nhà cung cấp không được để trống!");
            return false;
        }
        if (name.length() < 3 || name.length() > 50) {
            JOptionPane.showMessageDialog(this, "Tên nhà cung cấp phải từ 3 đến 50 ký tự!");
            return false;
        }
        if (!name.matches("^[a-zA-Z0-9 ]+$")) { // Chỉ cho phép chữ cái, số, và khoảng trắng
            JOptionPane.showMessageDialog(this, "Tên nhà cung cấp không được chứa ký tự đặc biệt!");
            return false;
        }

        // Kiểm tra số điện thoại
        if (sdt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không được để trống!");
            return false;
        }
        if (!sdt.matches("^[0-9]{10,11}$")) { // Chỉ cho phép số có 10-11 chữ số
            JOptionPane.showMessageDialog(this, "Số điện thoại phải từ 10 đến 11 số và chỉ chứa số!");
            return false;
        }

        // Kiểm tra địa chỉ
        if (diachi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Địa chỉ không được để trống!");
            return false;
        }
        if (diachi.length() < 5 || diachi.length() > 100) {
            JOptionPane.showMessageDialog(this, "Địa chỉ phải từ 5 đến 100 ký tự!");
            return false;
        }

        return true; // Nếu tất cả đều hợp lệ
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private DefaultTableModel tableModelNcc;

    private void taoBangTk() {
        tableModelNcc = new DefaultTableModel();
        tableModelNcc.setColumnIdentifiers(new String[]{
            "Mã nhà cung cấp", "Tên Nhà cung cấp", "Số điện thoại", "Địa chỉ", "Trạng thái"
        });
        jtbNcc.setModel(tableModelNcc);
    }
    private NhaCungCapBUS nccBUS = new NhaCungCapBUS();

    private void cacChucNang() {
        jtbNcc.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                clickChooseTbTk();
            }
        });
    }
    private int row = -1;

    private void clickChooseTbTk() {

        row = jtbNcc.getSelectedRow();
        if (row != -1) {
            btnAdd.setEnabled(false);
            txtIdncc.setText(jtbNcc.getValueAt(row, 0) + "");
            txtName.setText(jtbNcc.getValueAt(row, 1) + "");
            txtSdt.setText(jtbNcc.getValueAt(row, 2) + "");
            txtDiachi.setText(jtbNcc.getValueAt(row, 3) + "");
        }
    }

    private void hienthidsncc() {
        tableModelNcc.setRowCount(0);
        ArrayList<NhaCungCapDTO> lsNcc = nccBUS.lsNcc("");
        for (NhaCungCapDTO nccDto : lsNcc) {
            String trangThai = "Ngừng hợp tác!";
            if (nccDto.getDeleted() == 0) {
                trangThai = "Đang hợp tác!";
            }
            tableModelNcc.addRow(new Object[]{
                nccDto.getId(),
                nccDto.getNameNcc(),
                nccDto.getPhone(),
                nccDto.getAddress(),
                trangThai
            });
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbNcc = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnChinhtt = new javax.swing.JButton();
        txtIdncc = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiachi = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1125, 660));

        jtbNcc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbNcc);

        jLabel1.setText("Mã nhà cung cấp:");

        jLabel2.setText("Tên nhà cung cấp: ");

        jLabel3.setText("Số điện thoại: ");

        jLabel4.setText("Địa chỉ: ");

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnChinhtt.setText("Đổi trạng thái");
        btnChinhtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChinhttActionPerformed(evt);
            }
        });

        txtIdncc.setEditable(false);

        txtDiachi.setColumns(20);
        txtDiachi.setRows(5);
        jScrollPane2.setViewportView(txtDiachi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(55, 55, 55)
                            .addComponent(btnChinhtt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSdt, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(txtName)
                            .addComponent(txtIdncc))))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIdncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel4)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnChinhtt))
                .addGap(43, 43, 43)
                .addComponent(btnEdit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void refresh() {
        btnAdd.setEnabled(true);
        txtIdncc.setText("");
        txtName.setText("");
        txtSdt.setText("");
        txtDiachi.setText("");
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (validateFormAddNCC()) {
//            int idncc = Integer.parseInt(txtIdncc.getText());
            String nameNcc = txtName.getText();
            String sdt = txtSdt.getText();
            String diachi = txtDiachi.getText();

            if (nccBUS.themNcc(nameNcc, sdt, diachi)) {
                refresh();
                JOptionPane.showMessageDialog(null, "Thêm nhà cung cấp thành công!", "Success", JOptionPane.INFORMATION_MESSAGE);
                hienthidsncc();
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (validateFormNCC()) {
            int idncc = Integer.parseInt(txtIdncc.getText());
            String nameNcc = txtName.getText();
            String sdt = txtSdt.getText();
            String diachi = txtDiachi.getText();
            if (nccBUS.suaNcc(idncc, nameNcc, sdt, diachi)) {
                refresh();
                JOptionPane.showMessageDialog(null, "Cập nhật nhà cung cấp thành công!", "Success", JOptionPane.INFORMATION_MESSAGE);
                hienthidsncc();
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnChinhttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChinhttActionPerformed
        // TODO add your handling code here:
        if (validateFormNCC()) {
            int idncc = Integer.parseInt(txtIdncc.getText());
            int tt = nccBUS.layNccid(idncc).getDeleted();
            if (nccBUS.chinhTt(idncc, tt)) {
                refresh();
                JOptionPane.showMessageDialog(null, "Chỉnh sửa trạng thái thành công!", "Success", JOptionPane.INFORMATION_MESSAGE);
                hienthidsncc();
            }
        }
    }//GEN-LAST:event_btnChinhttActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnChinhtt;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtbNcc;
    private javax.swing.JTextArea txtDiachi;
    private javax.swing.JTextField txtIdncc;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSdt;
    // End of variables declaration//GEN-END:variables
}
