/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.BillBUS;
import BUS.ChiTietPhieuNhapBUS;
import BUS.SanPhamBUS;
import DTO.BillDTO;
import DTO.BillDetailsDTO;
import DTO.ChiTietPhieuNhapDTO;
import DTO.DsSpBanChay;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class thongke extends javax.swing.JPanel {

    /**
     * Creates new form thongke
     */
    public thongke() {
        initComponents();
        taoBangDsBanChay();
        layDsHoaDon();
        taoDsBanChay(listAllBill);
        hienThiDanhSach(topSellingMap);
    }
    private BillBUS billBUS = new BillBUS();
    private ArrayList<BillDTO> listAllBill = new ArrayList<>();
    private ArrayList<BillDTO> listBill = new ArrayList<>();

    private void layDsHoaDon() {
        listAllBill = billBUS.layDsHd();
    }

    private void locHoaDon(String bd, String kt) {
        listBill = new ArrayList<>();
        for (BillDTO bll : listAllBill) {
            String ngayTao = bll.getDayCreated().split(" ")[0];
            if (ngayTao.compareTo(bd) >= 0 && ngayTao.compareTo(kt) <= 0) {
                listBill.add(bll);
            }
        }
    }
    private HashMap<Integer, Integer> topSellingMap = new HashMap<>();
    private ChiTietPhieuNhapBUS ctpnBUS = new ChiTietPhieuNhapBUS();

    private void taoDsBanChay(ArrayList<BillDTO> list) {
        von = 0;
        thu=0;
        topSellingMap = new HashMap<>();
        for (BillDTO bllDto : list) {
            ArrayList<BillDetailsDTO> listBillDetails = billBUS.layCthd(bllDto.getId());
            String totalPayStr = bllDto.getTotalPay();
            double totalPay = (totalPayStr != null && !totalPayStr.trim().isEmpty())
                    ? Double.parseDouble(totalPayStr)
                    : 0.0;

            thu += totalPay;
            for (BillDetailsDTO bllDetails : listBillDetails) {
                ChiTietPhieuNhapDTO ctpnDto = ctpnBUS.layCtpnId(bllDetails.getIdGrnDetails());
                von = Double.parseDouble(ctpnDto.getIprice()) * bllDetails.getQuantity() + von;
                topSellingMap.put(bllDetails.getIdProduct(), topSellingMap.getOrDefault(bllDetails.getIdProduct(), 0) + bllDetails.getQuantity());
            }
        }
        txtDoanhthu.setText(String.valueOf(thu));
        txtLoinhuan.setText(String.valueOf(thu - von));
    }
    private DefaultTableModel tableModelBc;

    private void taoBangDsBanChay() {
        tableModelBc = new DefaultTableModel();
        tableModelBc.setColumnIdentifiers(new String[]{
            "Mã sản phẩm", "Tên sản phẩm", "Số lượng đã bán"
        });
        jtbBanchay.setModel(tableModelBc);
    }
    private SanPhamBUS spBUS = new SanPhamBUS();
//    private String tienVon="";
    private double thu = 0;
    private double von = 0;

    private void hienThiDanhSach(HashMap<Integer, Integer> mapp) {
        tableModelBc.setRowCount(0);
        List<Map.Entry<Integer, Integer>> sortedList = new ArrayList<>(mapp.entrySet());
        sortedList.sort((a, b) -> b.getValue().compareTo(a.getValue()));
        for (Map.Entry<Integer, Integer> entry : sortedList) {
            int productId = entry.getKey();
            int totalSold = entry.getValue();

            // Thêm dữ liệu vào bảng
            tableModelBc.addRow(new Object[]{
                productId,
                spBUS.laySpId(productId).getName(),
                totalSold
            });
        }

        tableModelBc.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void refresh() {
        txtDoanhthu.setText("");
        txtLoinhuan.setText("");
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDoanhthu = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtLoinhuan = new javax.swing.JTextField();
        txtNkt = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNbd = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbBanchay = new javax.swing.JTable();
        btnThongke = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1125, 660));

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel2.setText("Doanh thu: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtDoanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDoanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        jLabel4.setText("Lợi nhuận: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtLoinhuan, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLoinhuan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Ngày bắt đầu:");

        jLabel3.setText("Ngày kết thúc:");

        jtbBanchay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbBanchay);

        btnThongke.setText("Thống kê");
        btnThongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongkeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtNbd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtNkt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnThongke)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3))
                            .addComponent(txtNbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThongke))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNkt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongkeActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        Date dateNbd = txtNbd.getDate();
        Date dateNkt = txtNkt.getDate();

        String nbd = (dateNbd != null) ? sdf.format(dateNbd) : "";
        String nkt = (dateNkt != null) ? sdf.format(dateNkt) : "";
        locHoaDon(nbd, nkt);
        taoDsBanChay(listBill);
        hienThiDanhSach(topSellingMap);
    }//GEN-LAST:event_btnThongkeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThongke;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbBanchay;
    private javax.swing.JTextField txtDoanhthu;
    private javax.swing.JTextField txtLoinhuan;
    private com.toedter.calendar.JDateChooser txtNbd;
    private com.toedter.calendar.JDateChooser txtNkt;
    // End of variables declaration//GEN-END:variables
}
