/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.BillBUS;
import BUS.ChiTietPhieuNhapBUS;
import BUS.SanPhamBUS;
import DTO.BillDTO;
import DTO.BillDetailsDTO;
import DTO.ChiTietPhieuNhapDTO;
import DTO.DsSpBanChay;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class thongke extends javax.swing.JPanel {

    /**
     * Creates new form thongke
     */
    public thongke() {
        initComponents();
        taoBangDsBanChay();
        layDsHoaDon();
        taoDsBanChay(listAllBill);
        hienThiDanhSach(topSellingMap);
    }
    private BillBUS billBUS = new BillBUS();
    private ArrayList<BillDTO> listAllBill = new ArrayList<>();
    private ArrayList<BillDTO> listBill = new ArrayList<>();

    private void layDsHoaDon() {
        listAllBill = billBUS.layDsHd();
    }

    private void locHoaDon(String bd, String kt) {
        listBill = new ArrayList<>();
        for (BillDTO bll : listAllBill) {
            String ngayTao = bll.getDayCreated().split(" ")[0];
            if (ngayTao.compareTo(bd) >= 0 && ngayTao.compareTo(kt) <= 0) {
                listBill.add(bll);
            }
        }
    }
    private HashMap<Integer, Integer> topSellingMap = new HashMap<>();
    private ChiTietPhieuNhapBUS ctpnBUS = new ChiTietPhieuNhapBUS();

    private void taoDsBanChay(ArrayList<BillDTO> list) {
        von = 0;
        thu=0;
        topSellingMap = new HashMap<>();
        for (BillDTO bllDto : list) {
            ArrayList<BillDetailsDTO> listBillDetails = billBUS.layCthd(bllDto.getId());
            String totalPayStr = bllDto.getTotalPay();
            double totalPay = (totalPayStr != null && !totalPayStr.trim().isEmpty())
                    ? Double.parseDouble(totalPayStr)
                    : 0.0;

            thu += totalPay;
            for (BillDetailsDTO bllDetails : listBillDetails) {
                ChiTietPhieuNhapDTO ctpnDto = ctpnBUS.layCtpnId(bllDetails.getIdGrnDetails());
                von = Double.parseDouble(ctpnDto.getIprice()) * bllDetails.getQuantity() + von;
                topSellingMap.put(bllDetails.getIdProduct(), topSellingMap.getOrDefault(bllDetails.getIdProduct(), 0) + bllDetails.getQuantity());
            }
        }
        txtDoanhthu.setText(String.valueOf(thu));
        txtLoinhuan.setText(String.valueOf(thu - von));
    }
    private DefaultTableModel tableModelBc;

    private void taoBangDsBanChay() {
        tableModelBc = new DefaultTableModel();
        tableModelBc.setColumnIdentifiers(new String[]{
            "Mã sản phẩm", "Tên sản phẩm", "Số lượng đã bán"
        });
        jtbBanchay.setModel(tableModelBc);
    }
    private SanPhamBUS spBUS = new SanPhamBUS();
//    private String tienVon="";
    private double thu = 0;
    private double von = 0;

    private void hienThiDanhSach(HashMap<Integer, Integer> mapp) {
        tableModelBc.setRowCount(0);
        List<Map.Entry<Integer, Integer>> sortedList = new ArrayList<>(mapp.entrySet());
        sortedList.sort((a, b) -> b.getValue().compareTo(a.getValue()));
        for (Map.Entry<Integer, Integer> entry : sortedList) {
            int productId = entry.getKey();
            int totalSold = entry.getValue();

            // Thêm dữ liệu vào bảng
            tableModelBc.addRow(new Object[]{
                productId,
                spBUS.laySpId(productId).getName(),
                totalSold
            });
        }

        tableModelBc.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void refresh() {
        txtDoanhthu.setText("");
        txtLoinhuan.setText("");
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbBanchay = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtLoinhuan = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDoanhthu = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNbd = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtNkt = new com.toedter.calendar.JDateChooser();
        btnThongke = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1125, 660));
        setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jtbBanchay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbBanchay);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setRequestFocusEnabled(false);

        jLabel4.setText("Lợi nhuận: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtLoinhuan, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLoinhuan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel2.setText("Doanh thu: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtDoanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDoanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel1);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Ngày bắt đầu:");
        jPanel7.add(jLabel1);
        jPanel7.add(txtNbd);

        jLabel3.setText("Ngày kết thúc:");
        jPanel7.add(jLabel3);
        jPanel7.add(txtNkt);

        btnThongke.setBackground(new java.awt.Color(255, 153, 153));
        btnThongke.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnThongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/thongke.png"))); // NOI18N
        btnThongke.setMnemonic('t');
        btnThongke.setText("Thống kê");
        btnThongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongkeActionPerformed(evt);
            }
        });
        jPanel7.add(btnThongke);

        jPanel4.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel5.setBackground(new java.awt.Color(0, 102, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("THỐNG KÊ");
        jLabel5.setPreferredSize(new java.awt.Dimension(126, 40));
        jPanel5.add(jLabel5, java.awt.BorderLayout.CENTER);

        add(jPanel5, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongkeActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        Date dateNbd = txtNbd.getDate();
        Date dateNkt = txtNkt.getDate();

        String nbd = (dateNbd != null) ? sdf.format(dateNbd) : "";
        String nkt = (dateNkt != null) ? sdf.format(dateNkt) : "";
        locHoaDon(nbd, nkt);
        taoDsBanChay(listBill);
        hienThiDanhSach(topSellingMap);
    }//GEN-LAST:event_btnThongkeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThongke;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbBanchay;
    private javax.swing.JTextField txtDoanhthu;
    private javax.swing.JTextField txtLoinhuan;
    private com.toedter.calendar.JDateChooser txtNbd;
    private com.toedter.calendar.JDateChooser txtNkt;
    // End of variables declaration//GEN-END:variables
}
