/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.PermissionBUS;
import BUS.RoleBUS;
import BUS.RolePermissionBUS;
import DTO.PermissionDTO;
import DTO.RoleDTO;
import DTO.RolePermissionDTO;
import Util.dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class vaitro extends javax.swing.JPanel {

    /**
     * Creates new form vaitro
     */
    public vaitro() {
        initComponents();
        layDsVaitro();
        cacChucNang();
    }
    private RoleBUS roleBUS = new RoleBUS();
    private RolePermissionBUS rolePerBUS = new RolePermissionBUS();
    private ArrayList<RoleDTO> listRole = null;
    private Map<String, Integer> roleMap = new HashMap<>();
    private PermissionBUS perBUS = new PermissionBUS();

    private void cacChucNang() {
        cbbVaitro.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String selectedRole = (String) cbbVaitro.getSelectedItem();
                if (selectedRole != null && roleMap.containsKey(selectedRole)) {
                    int roleId = roleMap.get(selectedRole);
                    hienThiDanhSachQuyen(roleId);
                }
            }
        });
        jtbQuyen.getColumnModel().getColumn(3).setCellEditor(new javax.swing.DefaultCellEditor(new javax.swing.JCheckBox()));
        jtbQuyen.getDefaultEditor(Boolean.class).addCellEditorListener(new javax.swing.event.CellEditorListener() {
            @Override
            public void editingStopped(javax.swing.event.ChangeEvent e) {
                int row = jtbQuyen.getSelectedRow();
                if (row != -1) {
                    int permissionId = (int) jtbQuyen.getValueAt(row, 0);
                    boolean newState = (boolean) jtbQuyen.getValueAt(row, 3);
                    int has = newState ? 1 : 0;
                    int roleId = roleMap.get(cbbVaitro.getSelectedItem());

                    if (rolePerBUS.capNhapQuyenVaiTro(roleId, permissionId, has)) {
                        new dialog("Cập nhật quyền thành công!", dialog.SUCCESS_DIALOG);
                    }
                }
            }

            @Override
            public void editingCanceled(javax.swing.event.ChangeEvent e) {
                // Không cần xử lý gì khi chỉnh sửa bị hủy
            }
        });
    }

    private void hienThiDanhSachQuyen(int roleId) {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 3) {
                    return Boolean.class;
                }
                return String.class;
            }
        };

        model.setColumnIdentifiers(new String[]{"Mã quyền", "Tên quyền", "Mô tả", "Chọn"});
        jtbQuyen.setModel(model);
        ArrayList<RolePermissionDTO> rolePerList = rolePerBUS.layDsQuyen(roleId);
        for (RolePermissionDTO rolePer : rolePerList) {
            boolean choose = false;
            if (rolePer.getHas() == 1) {
                choose = true;
            }
            PermissionDTO per = perBUS.layPerId(rolePer.getPermissionId());
            model.addRow(new Object[]{rolePer.getPermissionId(), per.getCode(), per.getDescription(), choose});
        }
    }

    private void layDsVaitro() {
        listRole = roleBUS.layDsVaiTro();
        if (listRole == null || listRole.isEmpty()) {
            System.out.println("Danh sách vai trò rỗng!");
            return;
        }
        cbbVaitro.removeAllItems();
        roleMap.clear();
        DefaultTableModel model = new DefaultTableModel(
                new String[]{
                    "Mã Vai Trò", "Tên Vai Trò"
                },
                0
        );
        jtbDsvt.setModel(model);
        for (RoleDTO vt : listRole) {
            model.addRow(new Object[]{vt.getIdrole(), vt.getNamerole()});
            cbbVaitro.addItem(vt.getNamerole());
            roleMap.put(vt.getNamerole(), vt.getIdrole());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnTrai = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDsvt = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTenvaitro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtMavaitro = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jpnPhai = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbbVaitro = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbQuyen = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1125, 667));
        setLayout(new java.awt.BorderLayout());

        jpnTrai.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jtbDsvt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã vai trò", "Tên vai trò"
            }
        ));
        jScrollPane1.setViewportView(jtbDsvt);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("DANH SÁCH VAI TRÒ:");
        jLabel3.setPreferredSize(new java.awt.Dimension(119, 29));
        jPanel6.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jpnTrai.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(450, 160));

        jLabel2.setText("Tên vai trò: ");

        jLabel1.setText("Mã vai trò: ");

        txtMavaitro.setEditable(false);

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnDelete.setMnemonic('x');
        btnDelete.setText("XÓA");

        btnEdit.setBackground(new java.awt.Color(255, 255, 0));
        btnEdit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        btnEdit.setMnemonic('s');
        btnEdit.setText("SỬA");

        btnAdd.setBackground(new java.awt.Color(0, 204, 51));
        btnAdd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        btnAdd.setMnemonic('t');
        btnAdd.setText("THÊM");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenvaitro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMavaitro, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnAdd))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMavaitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenvaitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jpnTrai.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        add(jpnTrai, java.awt.BorderLayout.WEST);

        jpnPhai.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Vai trò:  ");

        cbbVaitro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbVaitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbVaitroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(cbbVaitro, 0, 600, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbVaitro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jpnPhai.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(51, 255, 51));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jtbQuyen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã quyền", "Tên quyền", "Mô tả", "Chọn"
            }
        ));
        jScrollPane2.setViewportView(jtbQuyen);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jpnPhai.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jpnPhai, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String name = txtTenvaitro.getText();
        if (roleBUS.ktTonTai(name)) {
            JOptionPane.showMessageDialog(null, "Vai trò đã tồn tại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (roleBUS.themVaiTro(name)) {
            RoleDTO roleDTO = roleBUS.layVtCuoi();
            if (rolePerBUS.themQuyenVaoVaiTro(roleDTO.getIdrole())) {
                JOptionPane.showMessageDialog(null, "Thêm vai trò thành công", "Success", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null, "Lỗi khi thêm quyền vào vai trò!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Lỗi thêm vai trò!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void cbbVaitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbVaitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbVaitroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<String> cbbVaitro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpnPhai;
    private javax.swing.JPanel jpnTrai;
    private javax.swing.JTable jtbDsvt;
    private javax.swing.JTable jtbQuyen;
    private javax.swing.JTextField txtMavaitro;
    private javax.swing.JTextField txtTenvaitro;
    // End of variables declaration//GEN-END:variables
}
