/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.PermissionBUS;
import BUS.RoleBUS;
import BUS.RolePermissionBUS;
import DTO.PermissionDTO;
import DTO.RoleDTO;
import DTO.RolePermissionDTO;
import Util.dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class vaitro extends javax.swing.JPanel {

    /**
     * Creates new form vaitro
     */
    public vaitro() {
        initComponents();
        layDsVaitro();
        cacChucNang();
    }
    private RoleBUS roleBUS = new RoleBUS();
    private RolePermissionBUS rolePerBUS = new RolePermissionBUS();
    private ArrayList<RoleDTO> listRole = null;
    private Map<String, Integer> roleMap = new HashMap<>();
    private PermissionBUS perBUS = new PermissionBUS();

    private void cacChucNang() {
        cbbVaitro.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String selectedRole = (String) cbbVaitro.getSelectedItem();
                if (selectedRole != null && roleMap.containsKey(selectedRole)) {
                    int roleId = roleMap.get(selectedRole);
                    hienThiDanhSachQuyen(roleId);
                }
            }
        });
        jtbQuyen.getColumnModel().getColumn(3).setCellEditor(new javax.swing.DefaultCellEditor(new javax.swing.JCheckBox()));
        jtbQuyen.getDefaultEditor(Boolean.class).addCellEditorListener(new javax.swing.event.CellEditorListener() {
            @Override
            public void editingStopped(javax.swing.event.ChangeEvent e) {
                int row = jtbQuyen.getSelectedRow();
                if (row != -1) {
                    int permissionId = (int) jtbQuyen.getValueAt(row, 0);
                    boolean newState = (boolean) jtbQuyen.getValueAt(row, 3);
                    int has = newState ? 1 : 0;
                    int roleId = roleMap.get(cbbVaitro.getSelectedItem());

                    if (rolePerBUS.capNhapQuyenVaiTro(roleId, permissionId, has)) {
                        new dialog("Cập nhật quyền thành công!", dialog.SUCCESS_DIALOG);
                    }
                }
            }

            @Override
            public void editingCanceled(javax.swing.event.ChangeEvent e) {
                // Không cần xử lý gì khi chỉnh sửa bị hủy
            }
        });
    }

    private void hienThiDanhSachQuyen(int roleId) {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 3) {
                    return Boolean.class;
                }
                return String.class;
            }
        };

        model.setColumnIdentifiers(new String[]{"Mã quyền", "Tên quyền", "Mô tả", "Chọn"});
        jtbQuyen.setModel(model);
        ArrayList<RolePermissionDTO> rolePerList = rolePerBUS.layDsQuyen(roleId);
        for (RolePermissionDTO rolePer : rolePerList) {
            boolean choose = false;
            if (rolePer.getHas() == 1) {
                choose = true;
            }
            PermissionDTO per = perBUS.layPerId(rolePer.getPermissionId());
            model.addRow(new Object[]{rolePer.getPermissionId(), per.getCode(), per.getDescription(), choose});
        }
    }

    private void layDsVaitro() {
        listRole = roleBUS.layDsVaiTro();
        if (listRole == null || listRole.isEmpty()) {
            System.out.println("Danh sách vai trò rỗng!");
            return;
        }
        cbbVaitro.removeAllItems();
        roleMap.clear();
        DefaultTableModel model = new DefaultTableModel(
                new String[]{
                    "Mã Vai Trò", "Tên Vai Trò"
                },
                0
        );
        jtbDsvt.setModel(model);
        for (RoleDTO vt : listRole) {
            model.addRow(new Object[]{vt.getIdrole(), vt.getNamerole()});
            cbbVaitro.addItem(vt.getNamerole());
            roleMap.put(vt.getNamerole(), vt.getIdrole());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnTrai = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMavaitro = new javax.swing.JTextField();
        txtTenvaitro = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDsvt = new javax.swing.JTable();
        jpnPhai = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbbVaitro = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbQuyen = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1125, 667));

        jLabel1.setText("Mã vai trò: ");

        jLabel2.setText("Tên vai trò: ");

        txtMavaitro.setEditable(false);

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Sửa");

        btnDelete.setText("Xóa");

        jLabel3.setText("Danh sách vai trò: ");

        jtbDsvt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã vai trò", "Tên vai trò"
            }
        ));
        jScrollPane1.setViewportView(jtbDsvt);

        javax.swing.GroupLayout jpnTraiLayout = new javax.swing.GroupLayout(jpnTrai);
        jpnTrai.setLayout(jpnTraiLayout);
        jpnTraiLayout.setHorizontalGroup(
            jpnTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTraiLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpnTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jpnTraiLayout.createSequentialGroup()
                        .addGroup(jpnTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpnTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMavaitro)
                            .addComponent(txtTenvaitro, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jpnTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAdd)
                            .addComponent(btnEdit)
                            .addComponent(btnDelete)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jpnTraiLayout.setVerticalGroup(
            jpnTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTraiLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpnTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMavaitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenvaitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit))
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel4.setText("Vai trò:  ");

        cbbVaitro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbVaitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbVaitroActionPerformed(evt);
            }
        });

        jtbQuyen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã quyền", "Tên quyền", "Mô tả", "Chọn"
            }
        ));
        jScrollPane2.setViewportView(jtbQuyen);

        javax.swing.GroupLayout jpnPhaiLayout = new javax.swing.GroupLayout(jpnPhai);
        jpnPhai.setLayout(jpnPhaiLayout);
        jpnPhaiLayout.setHorizontalGroup(
            jpnPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPhaiLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jpnPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPhaiLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbbVaitro, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jpnPhaiLayout.setVerticalGroup(
            jpnPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPhaiLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jpnPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbVaitro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnTrai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnPhai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnTrai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnPhai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String name = txtTenvaitro.getText();
        if (roleBUS.ktTonTai(name)) {
            JOptionPane.showMessageDialog(null, "Vai trò đã tồn tại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (roleBUS.themVaiTro(name)) {
            RoleDTO roleDTO = roleBUS.layVtCuoi();
            if (rolePerBUS.themQuyenVaoVaiTro(roleDTO.getIdrole())) {
                JOptionPane.showMessageDialog(null, "Thêm vai trò thành công", "Success", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null, "Lỗi khi thêm quyền vào vai trò!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Lỗi thêm vai trò!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void cbbVaitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbVaitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbVaitroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<String> cbbVaitro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpnPhai;
    private javax.swing.JPanel jpnTrai;
    private javax.swing.JTable jtbDsvt;
    private javax.swing.JTable jtbQuyen;
    private javax.swing.JTextField txtMavaitro;
    private javax.swing.JTextField txtTenvaitro;
    // End of variables declaration//GEN-END:variables
}
