/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.BillBUS;
import BUS.SanPhamBUS;
import DTO.BillDetailsDTO;
import DTO.SanPhamDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class xemCthd extends javax.swing.JPanel {

    /**
     * Creates new form xemCthd
     */
    public xemCthd() {
        initComponents();
    }
    private BillBUS billBUS = new BillBUS();
    private SanPhamBUS spBUS = new SanPhamBUS();
    private DefaultTableModel model;

    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   
    public void hienThiHoadon(int id) {
        ArrayList<BillDetailsDTO> dsCthd = billBUS.layCthd(id);

        // Kiểm tra nếu danh sách rỗng hoặc null
        if (dsCthd == null || dsCthd.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Không có dữ liệu hóa đơn!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Tạo model mới
        model = new DefaultTableModel(
                new String[]{"Mã hóa đơn", "Tên SP", "Số lượng", "Giá", "Tổng tiền"},
                0
        );

        for (BillDetailsDTO cthd : dsCthd) {
            // Lấy thông tin sản phẩm
            SanPhamDTO spDto = spBUS.laySpId(cthd.getIdProduct());
            String tenSanPham = (spDto != null) ? spDto.getName() : "Không tìm thấy";

            // Thêm dữ liệu vào model
            Object[] row = {
                cthd.getIdBill(),
                tenSanPham,
                cthd.getQuantity(),
                cthd.getPrice(),
                cthd.getTotalPay()
            };
            model.addRow(row);
        }

        jtbCthd.setModel(model); // Gán model mới cho bảng
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbCthd = new javax.swing.JTable();
        btnXuatexcel = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1125, 660));

        jtbCthd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbCthd);

        btnXuatexcel.setText("Xuất Excel ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXuatexcel)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnXuatexcel)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXuatexcel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbCthd;
    // End of variables declaration//GEN-END:variables
}
