/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.PhieuNhapBUS;
import BUS.SanPhamBUS;
import DTO.ChiTietPhieuNhapDTO;
import DTO.SanPhamDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class xemphieunhap extends javax.swing.JPanel {

    /**
     * Creates new form xemphieunhap
     */
    public xemphieunhap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private PhieuNhapBUS pnBUS = new PhieuNhapBUS();
    private SanPhamBUS spBUS = new SanPhamBUS();
    DefaultTableModel model;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbChitietphieunhap = new javax.swing.JTable();
        btnXuatexcel = new javax.swing.JButton();

        jtbChitietphieunhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbChitietphieunhap);

        btnXuatexcel.setText("Xuất Excel");
        btnXuatexcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatexcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXuatexcel)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXuatexcel)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void hienThiPhieuNhap(int id) {
        ArrayList<ChiTietPhieuNhapDTO> dsCtpn = pnBUS.layDsCtpnId(id);

        // Kiểm tra nếu danh sách rỗng hoặc null
        if (dsCtpn == null || dsCtpn.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Không có dữ liệu chi tiết phiếu nhập!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Tạo model mới
        DefaultTableModel model = new DefaultTableModel(
                new String[]{"Mã ctpn", "Mã phiếu nhập", "Mã SP", "Tên SP", "Số lượng", "Giá nhập", "%Lãi", "Giá bán"},
                0
        );

        for (ChiTietPhieuNhapDTO ctpn : dsCtpn) {
            // Lấy thông tin sản phẩm
            SanPhamDTO spDto = spBUS.laySpId(ctpn.getIdProduct());
            String tenSanPham = (spDto != null) ? spDto.getName() : "Không tìm thấy";

            // Thêm dữ liệu vào model
            Object[] row = {
                ctpn.getId(),
                ctpn.getIdGRN(),
                ctpn.getIdProduct(),
                tenSanPham,
                ctpn.getQuantity(),
                ctpn.getIprice(),
                ctpn.getInterestRate(),
                ctpn.getEprice()
            };
            model.addRow(row);
        }

        jtbChitietphieunhap.setModel(model); // Gán model mới cho bảng
    }

    private void btnXuatexcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatexcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXuatexcelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXuatexcel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbChitietphieunhap;
    // End of variables declaration//GEN-END:variables
}
